FROM node:16.20-alpine3.17 as build

WORKDIR /client

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /client/.output /usr/share/nginx/html